name: answer-query

on:
  discussion:
    types: [created, edited]

jobs:
  answer-query:
    name: answer-query
    runs-on: ubuntu-latest

    steps:

      - name: Test
        shell: bash
        env:
          DISCUSSION_BODY: ${{ github.event.discussion.body }}
        run: |
          echo "You said," $DISCUSSION_BODY
