name: answer-query

on:
  discussion:
    types: [created, edited]

jobs:
  answer-query:
    name: answer-query
    runs-on: ubuntu-latest

    steps:

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Get vector store
      #   shell: bash
      #   run: |
      #     export LATEST_TAG=`git describe --abbrev=0 --tags`
      #     wget https://github.com/hep-help/hooray/releases/download/$LATEST_TAG/hep-help-db.zip
      #     unzip hep-help-db.zip
      #     ls

      # - name: Get Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.11"

      # - name: Install dependencies
      #   run: |
      #     python -m pip install -r requirements.txt

      - name: Test
        shell: bash
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
          DISCUSSION_BODY: ${{ github.event.discussion.body }}
          DISCUSSION_ID: ${{ github.event.discussion.node_id }}
        run: |
          echo "You said," $DISCUSSION_BODY > output.md
          curl -v -X POST -H "Authorization: bearer $APP_TOKEN" -H "Content-Type: application/json" -d '{"query": "mutation { addDiscussionComment(input: {body: \"This is a test.\" discussionId: \"$DISCUSSION_ID\" clientMutationId: \"hep-helper\"}) { clientMutationId comment { id body } } }"}' https://api.github.com/graphql
