name: answer-query

on:
  discussion:
    types: [created, edited]

jobs:
  answer-query:
    name: answer-query
    runs-on: ubuntu-latest

    steps:

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test
        shell: bash
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
          DISCUSSION_BODY: ${{ github.event.discussion.body }}
          DISCUSSION_ID: ${{ github.event.discussion.node_id }}
        run: |
          echo "You said," $DISCUSSION_BODY > output.md
          curl -v -X POST -H "Authorization: bearer $APP_TOKEN" -H "Content-Type: application/json" -d '{"query": "mutation { addDiscussionComment(input: {body: \"This is a test.\" discussionId: \"$DISCUSSION_ID\" clientMutationId: \"hep-helper\"}) { clientMutationId comment { id body } } }"}' https://api.github.com/graphql
