name: to-vector-store

on:
  release:
    types:
      - published

jobs:
  to-vector-store:
    name: to-vector-store
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Build vector store
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -u scripts/to-vector-store.py

      - name: Zip vector store
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          zip -r hep-help-db

      - name: tmp debug
        run: |
          ls -lh

      - name: Upload as release file
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: softprops/action-gh-release@v1
        with:
          files: hep-help-db.zip
