name: to-vector-store

on:
  - workflow_dispatch
  - release

jobs:
  to-vector-store:
    name: to-vector-store
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          ls -R

      - name: Build vector store
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/to-vector-store.py

      - name: Quick check
        run: |
          ls -R
